### ISSUE TITLE
MISSING-TEXT-LINE-ACCTID-PROGRAMID-EMAIL2SUBJECT

### ISSUE THREAD

**Issue by coa0329** [coa0329/Bhaang#57] opened 2017-09-01 05:31 UTC
This should happen when you set schedule for email2 and email3 but you didn't set the content for them.

Solution : 
We should not allow user to set schedule for email2 or email3 until they save the content of them.

**Comment by coa0329** [comment] 2017-09-05 04:05
![104](https://user-images.githubusercontent.com/7914690/30044731-6b4bc35e-9229-11e7-827b-7c87628e6c61.JPG)

We will hide schedule for Email2 and Email3 in step3, if user didn't set the content of Email2 and Email3 in step2

**Comment by coa0329** [comment] 2017-09-05 04:06
![106](https://user-images.githubusercontent.com/7914690/30044838-239434d2-922a-11e7-8733-153b1afbfa0d.JPG)

Question : 
If user set the content of Email2 and Email3 but he doesn't set time in schedule. Should we set only days to their schedule ?

**Comment by coa0329** [comment] 2017-09-05 05:11
If user doesn't set time for email1 we will use the current time for email1 when user publish.
If user set schedule for email2 and email3 but he doesn't set time we will use time from email1.

**Comment by coa0329** [comment] 2017-09-05 09:21
Fixed hide schedule for email2 and email3 until user save them. 

Working on setting the time.

**Comment by coa0329** [comment] 2017-09-06 09:24
![111](https://user-images.githubusercontent.com/7914690/30104438-cfae69cc-931f-11e7-85bb-1461a24e6a9d.JPG)

We will show the popup if user doesn't enter date, time or timezone.

**Comment by coa0329** [comment] 2017-09-06 09:27
![112](https://user-images.githubusercontent.com/7914690/30104578-3d718ade-9320-11e7-8292-7338f0932efc.JPG)

We will show this popup if user set the PAST time in the schedule.

**Comment by daver78** [comment] 2017-09-06 15:45
@paagla123 Will test and verify this?  I will create a separate issue to give the pop-ups some love.

**Comment by paagla123** [comment] 2017-09-09 02:10
@coa0329 I cannot reproduce this. Can you pl tell me how to test this? Thx

**Comment by paagla123** [comment] 2017-09-12 00:46
This issue is fixed I believe - no longer getting the same error. Closing it.

**Closed by paagla123** 2017-09-12 00:46 UTC
Labels: bug
