### ISSUE TITLE
Dave, I need some help about CSS

### ISSUE THREAD

**Issue by jiewsone** [coa0329/Bhaang#83] opened 2017-09-06 09:51 UTC
Here is the page before load Landing Page Template.
![screen-before-loadtemplate](https://user-images.githubusercontent.com/30495168/30105219-28cb04dc-9322-11e7-894b-10dddcc0c555.JPG)

Then, we select template, CSS is broken.
![screen-after-loadtemplate](https://user-images.githubusercontent.com/30495168/30105376-9692694c-9322-11e7-82f9-e4a44fbdd289.JPG)

But in Dave mock up, everything look perfect.
How do you solve this problem?

**Comment by daver78** [comment] 2017-09-06 23:54
@jiewsone Happy to help.  I don't believe I ever had that exact problem, but similar things have happened to me elsewhere.  Usually, it is because I'm missing a closing <`div>` (or have too many `<div>`).  

Have you checked all parts of your HTML to ensure they're valid?

(PS: I have used various online tools to do this but I usually resort to checking opening and closing tags manually to figure out where the problem is.  I'm sure there has to be a better way but so far I haven't found a great tool for this.)

**Comment by daver78** [comment] 2017-09-07 23:29
@jiewsone I believe you figured this out?  If so, let's close this issue?

**Closed** 2017-09-08 01:46 UTC
Labels: help wanted
